### ISSUE TITLE
CodyFrame JavaScript components not working after following WordPress documentation

### ISSUE THREAD

**Issue by mustardBees** [CodyHouse/codyhouse-wp-config#1]
I was missing the following in the document head:

```html
<script>document.getElementsByTagName("html")[0].className += " js";</script>
```

Worth a mention in the [WordPress setup documentation](https://codyhouse.co/ds/docs/framework#wp), perhaps include a snippet to hook this into the WordPress head.

**Comment by claudia-romano** [comment]
Hi, thanks for the heads up. We have added it to our documentation page:
https://codyhouse.co/ds/docs/framework#wp

Cheers!
