### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by n8bitsats** [CodyHouse/codyhouse-wp-config#2]
Everything was working fine last night but I woke up to this compilation error:

Compilation Error
Error: File "/Applications/MAMP/htdocs/wordpress/wp-content/themes/polygon-v2/assets/css/components/**/*.scss" not found
        on line 3 of sass/Applications/MAMP/htdocs/wordpress/wp-content/themes/polygon-v2/assets/css/style.scss
>> @import 'components/**/*.scss';
   --------^

It makes no sense as everything is where it should be and it was working fine when I left it.

**Comment by claudia-romano** [comment]
Hi there,
did you install the gulp-sass-glob module? 
If you did, then make sure the relative path to the folder is correct as the module is not able to find the components folder.

**Comment by claudia-romano** [comment]
Closing this as no additional info was provided. Feel free to reopen it if you are still experiencing this issue. Cheers!
