### ISSUE TITLE
Issues on npm install

### ISSUE THREAD

**Issue by pgroot91** [CodyHouse/codyhouse-wp-config#3]
Currently facing issues on npm install.

I didn't have any issues before but currently facing the following issue and have no clue how to solve it.

```
C:\xampp\htdocs\WH33LS Landingspage\wp-content\themes\wh33lseu>npm install
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated debug@4.1.1: Debug versions >=3.2.0 <3.2.7 || >=4 <4.3.1 have a low-severity ReDos regression when used in a Node.js environment. It is recommended you upgrade to 3.2.7 or 4.3.1. (https://github.com/visionmedia/debug/issues/797)
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -4058
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/CodyHouse/postcss-css-variables.git
npm ERR! enoent
npm ERR! enoent
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```

**Comment by pgroot91** [comment]
just replaced the following in the package.json on line 32:
`"postcss-css-variables": "git+https://github.com/CodyHouse/postcss-css-variables"`

with the following:
`"postcss-css-variables": "^0.17.0"`

Hope this solves it and install seems to be fine. 🤞

**Comment by claudia-romano** [comment]
Hi there,
we use a modified version of the postcss-css-variables module, this is why you should use "git+https://github.com/CodyHouse/postcss-css-variables". 

Here's the GitHub folder:
https://github.com/CodyHouse/postcss-css-variables

It is possible there was a temporary issue with GitHub so it was not possible to download the module. I just checked and everything is working fine now.

I'm closing this issue, but feel free to reopen it if you are still experiencing the same problem. Cheers!
